const ificationContent = [
  {
    title:"有声书",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"畅销书",
    content:[
      {text:"社科"},
      {text:"经管"},
      {text:"文学"},
      {text:"励志"},
      {text:"名著"},
      {text:"生活"}
    ]
  },
  {
    title:"儿童",
    content:[
      {text:"故事"},
      {text:"儿歌"},
      {text:"动画"},
      {text:"科普"},
      {text:"名著"},
      {text:"国学"}
    ]
  },
  {
    title:"相声评书",
    content:[
      {text:"单田芳"},
      {text:"郭德纲"},
      {text:"热门相声"},
      {text:"单口相声"},
      {text:"名家评书"},
      {text:"新锐笑将"}
    ]
  },
  {
    title:"情感生活",
    content:[
      {text:"恋爱技巧"},
      {text:"睡前夜话"},
      {text:"情绪压力"},
      {text:"婚姻家庭"},
      {text:"个人成长"},
      {text:"心理健康"}
    ]
  },
  {
    title:"人文",
    content:[
      {text:"诗词歌赋"},
      {text:"百家讲坛"},
      {text:"文学名著"},
      {text:"文化杂谈"},
      {text:"纪实故事"},
      {text:"艺术"}
    ]
  },
  {
    title:"历史",
    content:[
      {text:"世界历史"},
      {text:"中国通史"},
      {text:"二战"}

    ]
  },
  {
    title:"国学书院",
    content:[
      {text:"周易"},
      {text:"诸子百家"},
      {text:"四大名著"},
      {text:"道德经"},
      {text:"论语"},
      {text:"道家"}
    ]
  },
  {
    title:"音乐",
    content:[
      {text:"音乐节目"},
      {text:"电音"},
      {text:"流行音乐"},
      {text:"民谣"},
      {text:"摇滚"},
      {text:"经典音乐"}
    ]
  },
  {
    title:"教育培训",
    content:[
      {text:"考研"},
      {text:"考公"},
      {text:"法考"},
      {text:"自考"},
      {text:"互联网运营"},
      {text:"互联网节目"}
    ]
  },
  {
    title:"体育",
    content:[
      {text:"跑步"},
      {text:"健身"},
      {text:"足球"},
      {text:"瑜伽"},
      {text:"NBA"},
      {text:"英超"}
    ]
  },
]

module.exports = {
  ificationContent
}